package detect

var detectionRules = []DetectionRule{
	{Technology: Git, Files: []string{".git"}, Desc: "Git repository"},
	{Technology: Go, Files: []string{"go.mod", "*.go"}, Desc: "Go module or Go files"},
	{Technology: NodeJS, Files: []string{"package.json"}, Desc: "Node.js package"},
	{Technology: React, Files: []string{"*.jsx", "*.tsx"}, Desc: "React project"},
	{Technology: Vue, Files: []string{"*.vue", "vue.config.js", "vue.config.ts"}, Desc: "Vue.js project"},
	{Technology: Svelte, Files: []string{"*.svelte", "svelte.config.js", "vite.config.js"}, Desc: "Svelte project"},
	{Technology: NextJS, Files: []string{"next.config.js", "next.config.mjs", "next.config.ts"}, Desc: "Next.js project"},
	{Technology: Nuxt, Files: []string{"nuxt.config.js", "nuxt.config.ts"}, Desc: "Nuxt.js project"},
	{Technology: Angular, Files: []string{"angular.json", "*.component.ts"}, Desc: "Angular project"},
	{Technology: Python, Files: []string{"requirements.txt", "setup.py", "pyproject.toml", "Pipfile"}, Desc: "Python project"},
	{Technology: Rust, Files: []string{"Cargo.toml"}, Desc: "Rust project"},
	{Technology: Ruby, Files: []string{"Gemfile"}, Desc: "Ruby project"},
	{Technology: Java, Files: []string{"pom.xml", "build.gradle"}, Desc: "Java project"},
	{Technology: Clojure, Files: []string{"project.clj", "deps.edn", "shadow-cljs.edn", "bb.edn"}, Desc: "Clojure project"},
	{Technology: Transcript, Files: []string{"*.cmdt"}, Desc: "Transcript test files"},
	{Technology: Hurl, Files: []string{"*.hurl"}, Desc: "Hurl HTTP test files"},
	{Technology: C, Files: []string{"*.c", "*.h"}, Desc: "C source files"},
	{Technology: Cpp, Files: []string{"*.cpp", "*.cc", "*.cxx", "*.hpp", "*.hh", "*.hxx"}, Desc: "C++ source files"},
	{Technology: TypeScript, Files: []string{"*.ts", "*.dts"}, Desc: "TypeScript source files"},
	{Technology: JavaScript, Files: []string{"*.js", "*.mjs", "*.cjs"}, Desc: "JavaScript source files"},
	{Technology: Swift, Files: []string{"*.swift"}, Desc: "Swift source files"},
	{Technology: Kotlin, Files: []string{"*.kt", "*.kts"}, Desc: "Kotlin source files"},
	{Technology: CSharp, Files: []string{"*.cs"}, Desc: "C# source files"},
	{Technology: PHP, Files: []string{"*.php"}, Desc: "PHP source files"},
	{Technology: Dart, Files: []string{"*.dart"}, Desc: "Dart source files"},
	{Technology: Haskell, Files: []string{"*.hs"}, Desc: "Haskell source files"},
	{Technology: Perl, Files: []string{"*.pl"}, Desc: "Perl source files"},
	{Technology: Lua, Files: []string{"*.lua"}, Desc: "Lua source files"},
	{Technology: Shell, Files: []string{"*.sh", "*.bash", "*.zsh", "*.fish"}, Desc: "Shell scripts"},
	{Technology: Markdown, Files: []string{"*.md", "*.markdown"}, Desc: "Markdown files"},
	{Technology: HTML, Files: []string{"*.html", "*.htm"}, Desc: "HTML files"},
	{Technology: CSS, Files: []string{"*.css", "*.scss", "*.sass", "*.less"}, Desc: "CSS and preprocessor files"},
	{Technology: OCaml, Files: []string{"*.ml", "*.mli"}, Desc: "OCaml source files"},
	{Technology: VimScript, Files: []string{"*.vim"}, Desc: "Vim script files"},
	{Technology: Assembly, Files: []string{"*.asm", "*.s", "*.S"}, Desc: "Assembly source files"},
	{Technology: CoffeeScript, Files: []string{"*.coffee"}, Desc: "CoffeeScript source files"},
	{Technology: Elixir, Files: []string{"*.ex", "*.exs"}, Desc: "Elixir source files"},
	{Technology: Erlang, Files: []string{"*.erl"}, Desc: "Erlang source files"},
	{Technology: Fortran, Files: []string{"*.f90"}, Desc: "Fortran source files"},
	{Technology: Zig, Files: []string{"*.zig"}, Desc: "Zig source files"},
	{Technology: JSON, Files: []string{"*.json"}, Desc: "JSON files"},
	{Technology: YAML, Files: []string{"*.yaml", "*.yml"}, Desc: "YAML files"},
	{Technology: XML, Files: []string{"*.xml"}, Desc: "XML files"},
	{Technology: SQL, Files: []string{"*.sql"}, Desc: "SQL files"},
	{Technology: ProtocolBuffers, Files: []string{"*.proto"}, Desc: "Protocol Buffer files"},
	{Technology: GraphQL, Files: []string{"*.graphql", "*.gql"}, Desc: "GraphQL files"},
	{Technology: R, Files: []string{"*.r", "*.R"}, Desc: "R source files"},
	{Technology: TOML, Files: []string{"*.toml"}, Desc: "TOML files"},
	{Technology: INI, Files: []string{"*.ini", "*.cfg", "*.conf"}, Desc: "INI/Config files"},
	{Technology: LaTeX, Files: []string{"*.tex"}, Desc: "LaTeX files"},
	{Technology: PowerShell, Files: []string{"*.ps1"}, Desc: "PowerShell scripts"},
	{Technology: Batch, Files: []string{"*.bat", "*.cmd"}, Desc: "Batch files"},
	{Technology: Make, Files: []string{"Makefile", "makefile", "*.mk"}, Desc: "Makefiles"},
}
