package detect

// Detection rules are sorted alphabetically by technology to minimize merge conflicts
// when adding new rules. Please maintain this order.
var detectionRules = []DetectionRule{
	{Technology: Angular, Files: []string{"angular.json", "*.component.ts"}, Desc: "Angular project", URL: "https://angular.io"},
	{Technology: Assembly, Files: []string{"*.asm", "*.s", "*.S"}, Desc: "Assembly source files", URL: "https://en.wikipedia.org/wiki/Assembly_language"},
	{Technology: Batch, Files: []string{"*.bat", "*.cmd"}, Desc: "Batch files", URL: "https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands"},
	{Technology: C, Files: []string{"*.c", "*.h"}, Desc: "C source files", URL: "https://en.wikipedia.org/wiki/C_(programming_language)"},
	{Technology: Clojure, Files: []string{"project.clj", "deps.edn", "shadow-cljs.edn", "bb.edn"}, Desc: "Clojure project", URL: "https://clojure.org"},
	{Technology: CoffeeScript, Files: []string{"*.coffee"}, Desc: "CoffeeScript source files", URL: "https://coffeescript.org"},
	{Technology: Cpp, Files: []string{"*.cpp", "*.cc", "*.cxx", "*.hpp", "*.hh", "*.hxx"}, Desc: "C++ source files", URL: "https://isocpp.org"},
	{Technology: CSS, Files: []string{"*.css", "*.scss", "*.sass", "*.less"}, Desc: "CSS and preprocessor files", URL: "https://developer.mozilla.org/en-US/docs/Web/CSS"},
	{Technology: CSharp, Files: []string{"*.cs"}, Desc: "C# source files", URL: "https://docs.microsoft.com/en-us/dotnet/csharp/"},
	{Technology: Dart, Files: []string{"*.dart"}, Desc: "Dart source files", URL: "https://dart.dev"},
	{Technology: Direnv, Files: []string{".envrc"}, Desc: "Direnv environment configuration", URL: "https://direnv.net"},
	{Technology: Elixir, Files: []string{"*.ex", "*.exs"}, Desc: "Elixir source files", URL: "https://elixir-lang.org"},
	{Technology: Erlang, Files: []string{"*.erl"}, Desc: "Erlang source files", URL: "https://www.erlang.org"},
	{Technology: Fortran, Files: []string{"*.f90"}, Desc: "Fortran source files", URL: "https://fortran-lang.org"},
	{Technology: Git, Files: []string{".git"}, Desc: "Git repository", URL: "https://git-scm.com"},
	{Technology: Go, Files: []string{"go.mod", "*.go"}, Desc: "Go module or Go files", URL: "https://golang.org"},
	{Technology: GraphQL, Files: []string{"*.graphql", "*.gql"}, Desc: "GraphQL files", URL: "https://graphql.org"},
	{Technology: Haskell, Files: []string{"*.hs"}, Desc: "Haskell source files", URL: "https://www.haskell.org"},
	{Technology: HTML, Files: []string{"*.html", "*.htm"}, Desc: "HTML files", URL: "https://developer.mozilla.org/en-US/docs/Web/HTML"},
	{Technology: Hurl, Files: []string{"*.hurl"}, Desc: "Hurl HTTP test files", URL: "https://hurl.dev"},
	{Technology: INI, Files: []string{"*.ini", "*.cfg", "*.conf"}, Desc: "INI/Config files", URL: "https://en.wikipedia.org/wiki/INI_file"},
	{Technology: Java, Files: []string{"pom.xml", "build.gradle"}, Desc: "Java project", URL: "https://www.oracle.com/java/"},
	{Technology: JavaScript, Files: []string{"*.js", "*.mjs", "*.cjs"}, Desc: "JavaScript source files", URL: "https://developer.mozilla.org/en-US/docs/Web/JavaScript"},
	{Technology: JSON, Files: []string{"*.json"}, Desc: "JSON files", URL: "https://www.json.org"},
	{Technology: Kotlin, Files: []string{"*.kt", "*.kts"}, Desc: "Kotlin source files", URL: "https://kotlinlang.org"},
	{Technology: LaTeX, Files: []string{"*.tex"}, Desc: "LaTeX files", URL: "https://www.latex-project.org"},
	{Technology: Lua, Files: []string{"*.lua"}, Desc: "Lua source files", URL: "https://www.lua.org"},
	{Technology: Make, Files: []string{"Makefile", "makefile", "*.mk"}, Desc: "Makefiles", URL: "https://www.gnu.org/software/make/"},
	{Technology: Markdown, Files: []string{"*.md", "*.markdown"}, Desc: "Markdown files", URL: "https://daringfireball.net/projects/markdown/"},
	{Technology: NextJS, Files: []string{"next.config.js", "next.config.mjs", "next.config.ts"}, Desc: "Next.js project", URL: "https://nextjs.org"},
	{Technology: NodeJS, Files: []string{"package.json"}, Desc: "Node.js package", URL: "https://nodejs.org"},
	{Technology: Nuxt, Files: []string{"nuxt.config.js", "nuxt.config.ts"}, Desc: "Nuxt.js project", URL: "https://nuxtjs.org"},
	{Technology: OCaml, Files: []string{"*.ml", "*.mli"}, Desc: "OCaml source files", URL: "https://ocaml.org"},
	{Technology: Perl, Files: []string{"*.pl"}, Desc: "Perl source files", URL: "https://www.perl.org"},
	{Technology: PHP, Files: []string{"*.php"}, Desc: "PHP source files", URL: "https://www.php.net"},
	{Technology: PowerShell, Files: []string{"*.ps1"}, Desc: "PowerShell scripts", URL: "https://docs.microsoft.com/en-us/powershell/"},
	{Technology: Procfile, Files: []string{"Procfile"}, Desc: "Procfile for process management", URL: "https://devcenter.heroku.com/articles/procfile"},
	{Technology: ProtocolBuffers, Files: []string{"*.proto"}, Desc: "Protocol Buffer files", URL: "https://developers.google.com/protocol-buffers"},
	{Technology: Python, Files: []string{"requirements.txt", "setup.py", "pyproject.toml", "Pipfile"}, Desc: "Python project", URL: "https://www.python.org"},
	{Technology: R, Files: []string{"*.r", "*.R"}, Desc: "R source files", URL: "https://www.r-project.org"},
	{Technology: React, Files: []string{"*.jsx", "*.tsx"}, Desc: "React project", URL: "https://reactjs.org"},
	{Technology: Ruby, Files: []string{"Gemfile"}, Desc: "Ruby project", URL: "https://www.ruby-lang.org"},
	{Technology: Rust, Files: []string{"Cargo.toml"}, Desc: "Rust project", URL: "https://www.rust-lang.org"},
	{Technology: Shell, Files: []string{"*.sh", "*.bash", "*.zsh", "*.fish"}, Desc: "Shell scripts", URL: "https://en.wikipedia.org/wiki/Unix_shell"},
	{Technology: SQL, Files: []string{"*.sql"}, Desc: "SQL files", URL: "https://en.wikipedia.org/wiki/SQL"},
	{Technology: Svelte, Files: []string{"*.svelte", "svelte.config.js", "vite.config.js"}, Desc: "Svelte project", URL: "https://svelte.dev"},
	{Technology: Swift, Files: []string{"*.swift"}, Desc: "Swift source files", URL: "https://swift.org"},
	{Technology: TOML, Files: []string{"*.toml"}, Desc: "TOML files", URL: "https://toml.io"},
	{Technology: Transcript, Files: []string{"*.cmdt"}, Desc: "Transcript test files", URL: "https://github.com/brandonbloom/transcript"},
	{Technology: TypeScript, Files: []string{"*.ts", "*.dts"}, Desc: "TypeScript source files", URL: "https://www.typescriptlang.org"},
	{Technology: VimScript, Files: []string{"*.vim"}, Desc: "Vim script files", URL: "https://www.vim.org"},
	{Technology: Vue, Files: []string{"*.vue", "vue.config.js", "vue.config.ts"}, Desc: "Vue.js project", URL: "https://vuejs.org"},
	{Technology: XML, Files: []string{"*.xml"}, Desc: "XML files", URL: "https://www.w3.org/XML/"},
	{Technology: YAML, Files: []string{"*.yaml", "*.yml"}, Desc: "YAML files", URL: "https://yaml.org"},
	{Technology: Zig, Files: []string{"*.zig"}, Desc: "Zig source files", URL: "https://ziglang.org"},
}
