package detect

type Technology string

// Technology constants are sorted alphabetically to minimize merge conflicts
// when adding new technologies. Please maintain this order.
const (
	Angular         Technology = "angular"
	Assembly        Technology = "assembly"
	Batch           Technology = "batch"
	C               Technology = "c"
	Clojure         Technology = "clojure"
	CoffeeScript    Technology = "coffeescript"
	Cpp             Technology = "cpp"
	CSS             Technology = "css"
	CSharp          Technology = "csharp"
	Dart            Technology = "dart"
	Direnv          Technology = "direnv"
	Elixir          Technology = "elixir"
	Erlang          Technology = "erlang"
	Fortran         Technology = "fortran"
	Git             Technology = "git"
	Go              Technology = "go"
	GraphQL         Technology = "graphql"
	Haskell         Technology = "haskell"
	HTML            Technology = "html"
	Hurl            Technology = "hurl"
	INI             Technology = "ini"
	Java            Technology = "java"
	JavaScript      Technology = "javascript"
	JSON            Technology = "json"
	Kotlin          Technology = "kotlin"
	LaTeX           Technology = "latex"
	Lua             Technology = "lua"
	Make            Technology = "make"
	Markdown        Technology = "markdown"
	NextJS          Technology = "nextjs"
	NodeJS          Technology = "nodejs"
	Nuxt            Technology = "nuxt"
	OCaml           Technology = "ocaml"
	Perl            Technology = "perl"
	PHP             Technology = "php"
	PowerShell      Technology = "powershell"
	Procfile        Technology = "procfile"
	ProtocolBuffers Technology = "protobuf"
	Python          Technology = "python"
	R               Technology = "r"
	React           Technology = "react"
	Ruby            Technology = "ruby"
	Rust            Technology = "rust"
	Shell           Technology = "shell"
	SQL             Technology = "sql"
	Svelte          Technology = "svelte"
	Swift           Technology = "swift"
	TOML            Technology = "toml"
	Transcript      Technology = "transcript"
	TypeScript      Technology = "typescript"
	VimScript       Technology = "vimscript"
	Vue             Technology = "vue"
	XML             Technology = "xml"
	YAML            Technology = "yaml"
	Zig             Technology = "zig"
)
